### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by setvisible** [comment]
Great job !

**Comment by Vistaus** [comment]
@setvisible Thanks! 🙂

**Comment by setvisible** [comment]
Hi Vistaus,

I uploaded your files to Transifex (translation tool). I also added the webextension and launcher translations.
If you want to contribute to them too, they are modifiable here:
https://www.transifex.com/downzemall/downzemall/

Let me know if so, in order to grant you as Reviewer and Translator.

Thank you again for the amazing job done !
 
Regards

**Comment by Vistaus** [comment]
Hi @setvisible,

No problem - my pleasure! 🙂 Thanks for adding the translation to Transifex as well. That will make it easier to keep it up-to-date. I will request to join the team so that you can add me as reviewer and translator.

Regards,
Vistaus

**Pull request merged**
